import * as angular from "angular";
import {background} from "./background/background";
import {topBar} from "./top-bar/top-bar";
import {stories} from "./stories/stories/stories";
import {storyNode} from "./stories/story-node/story-node";
import {storyBrief} from "./stories/story-brief/story-brief";
import {storyDetail} from "./stories/story-detail/story-detail";
import {entities} from "./entities/entitites/entities";
import {entityDetail} from "./entities/entity-detail/entity-detail";
import {mapIcon} from "./maps/map-icon/map-icon";
import {combat} from "./combat/combat";
import {entityDetailRoute} from "./entities/entity-detail-route/entity-detail-route";
import {note} from "./notes/note/note";
import {notes} from "./notes/notes/notes";
import {map} from "./maps/map/map";
import {mapLegend} from "./maps/map-legend/map-legend";
import {synopsis} from "./synopsis/synopsis/synopsis";
import {encounter} from "./maps/encounter/encounter";
import {playerVisible} from "./player-access/player-visible/player-visible";
import {playerClickable} from "./player-access/player-clickable/player-clickable";
import {login} from "./login/login";

export function initComponents(app: angular.IModule) {
    app.component("topBar", topBar);
    app.component("login", login);
    app.component("background", background);
    app.component("synopsis", synopsis);
    app.component("story", stories);
    app.component("storyNode", storyNode);
    app.component("storyBrief", storyBrief);
    app.component("storyDetail", storyDetail);
    app.component("map", map);
    app.component("mapIcon", mapIcon);
    app.component("mapLegend", mapLegend);
    app.component("encounter", encounter);
    app.component("entities", entities);
    app.component("entityDetail", entityDetail);
    app.component("entityDetailRoute", entityDetailRoute);
    app.component("combat", combat);
    app.component("note", note);
    app.component("notes", notes);
    app.directive("playerVisible", () => playerVisible);
    app.directive("playerClickable", () => playerClickable);
}
